import zipfile
import io
from typing import Dict, Optional


class ExportService:
    """项目导出服务 — 将生成的文件打包为 ZIP"""
    
    @staticmethod
    def create_project_files(html_content: str, project_name: str = "pageforge-project") -> Dict[str, str]:
        """创建完整的前端项目文件结构"""
        files = {}
        
        # package.json
        files["package.json"] = '''{
  "name": "''' + project_name + '''",
  "version": "1.0.0",
  "description": "Generated by PageForge",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {},
  "devDependencies": {
    "vite": "^5.0.0"
  }
}'''
        
        # index.html
        files["index.html"] = html_content
        
        # vite.config.js
        files["vite.config.js"] = '''import { defineConfig } from 'vite'

export default defineConfig({
  server: {
    port: 3000,
    open: true
  }
})'''
        
        # README.md
        files["README.md"] = f'''# {project_name}

Generated by PageForge

## Getting Started

```bash
npm install
npm run dev
```

## Build

```bash
npm run build
```'''
        
        return files
    
    @staticmethod
    def create_zip(files: Dict[str, str]) -> bytes:
        """将文件打包为 ZIP"""
        zip_buffer = io.BytesIO()
        
        with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
            for filename, content in files.items():
                zip_file.writestr(filename, content)
        
        zip_buffer.seek(0)
        return zip_buffer.read()
    
    @staticmethod
    def export_project(html_content: str, project_name: str = "pageforge-project") -> bytes:
        """导出完整项目"""
        files = ExportService.create_project_files(html_content, project_name)
        return ExportService.create_zip(files)
